
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Button processButton;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView outputTextview;
	
	private global::Gtk.Button processIviVisaButton;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.processButton = new global::Gtk.Button ();
		this.processButton.CanFocus = true;
		this.processButton.Name = "processButton";
		this.processButton.UseUnderline = true;
		this.processButton.Label = global::Mono.Unix.Catalog.GetString ("Process NI");
		this.fixed1.Add (this.processButton);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.processButton]));
		w1.X = 19;
		w1.Y = 286;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.outputTextview = new global::Gtk.TextView ();
		this.outputTextview.WidthRequest = 200;
		this.outputTextview.HeightRequest = 250;
		this.outputTextview.CanFocus = true;
		this.outputTextview.Name = "outputTextview";
		this.GtkScrolledWindow.Add (this.outputTextview);
		this.fixed1.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
		w3.X = 23;
		w3.Y = 11;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.processIviVisaButton = new global::Gtk.Button ();
		this.processIviVisaButton.CanFocus = true;
		this.processIviVisaButton.Name = "processIviVisaButton";
		this.processIviVisaButton.UseUnderline = true;
		this.processIviVisaButton.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.fixed1.Add (this.processIviVisaButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.processIviVisaButton]));
		w4.X = 144;
		w4.Y = 287;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 460;
		this.DefaultHeight = 525;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.processButton.Clicked += new global::System.EventHandler (this.processButton_Click);
		this.processIviVisaButton.Clicked += new global::System.EventHandler (this.processIviVisaButton_Click);
	}
}
